version: '3'
services:
  local:
    image: cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "3000:3000"
    - "6006:6006"
    volumes:
    - .:/yorudokimayu-info
    working_dir: /yorudokimayu-info
    entrypoint: yarn
    command: dev