version: '3'
services:
  local:
    image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "3000:3000"
    - "6006:6006"
    volumes:
    - .:/yorudokimayu-info
    working_dir: /yorudokimayu-info
    entrypoint: yarn
    command: dev