version: '3'
services:
  local:
    build:
      dockerfile: DockerfileCypress
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "3000:3000"
    - "6006:6006"
    volumes:
    - .:/yorudokimayu-info
    working_dir: /yorudokimayu-info
    entrypoint: yarn
    command: dev