version: '3'
services:
  local:
    image: cypress/browsers:node-22.12.0-chrome-131.0.6778.139-1-ff-133.0.3-edge-131.0.2903.99-1
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "3000:3000"
    - "6006:6006"
    volumes:
    - .:/yorudokimayu-info
    working_dir: /yorudokimayu-info
    entrypoint: yarn
    command: dev