name: Cypress

on: 
  pull_request:
    branches:    
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
          config: baseUrl=http://localhost:3000